# Generated by Django 5.0.1 on 2024-10-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfe', '0002_notacte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacte',
            name='destinatario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notacte',
            name='destinatario_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='destinatario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='destinatario_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
